"""empty message

Revision ID: 79db18af101b
Revises: 
Create Date: 2023-04-21 08:33:18.193266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79db18af101b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h_addresses',
    sa.Column('h_address_id', sa.Integer(), nullable=False),
    sa.Column('h_address', sa.Text(), nullable=False),
    sa.Column('h_address_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('h_address_id'),
    sa.UniqueConstraint('h_address')
    )
    op.create_table('h_chains',
    sa.Column('h_chain_id', sa.Integer(), nullable=False),
    sa.Column('h_network_name', sa.Text(), nullable=False),
    sa.Column('h_native_chain_token', sa.Text(), nullable=False),
    sa.Column('h_network_rpc_node', sa.Text(), nullable=False),
    sa.Column('h_network_block_limit', sa.Integer(), nullable=False),
    sa.Column('h_network_uri', sa.Text(), nullable=False),
    sa.Column('h_network_api_key', sa.Text(), nullable=False),
    sa.Column('h_network_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('h_chain_id'),
    sa.UniqueConstraint('h_network_name')
    )
    op.create_table('h_protocols',
    sa.Column('h_protocol_id', sa.Integer(), nullable=False),
    sa.Column('h_protocol_name', sa.Text(), nullable=False),
    sa.Column('h_protocol_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('h_protocol_id'),
    sa.UniqueConstraint('h_protocol_name')
    )
    op.create_table('h_specifications',
    sa.Column('h_specification_id', sa.Integer(), nullable=False),
    sa.Column('h_specification_name', sa.Text(), nullable=False),
    sa.Column('h_address_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('h_specification_id'),
    sa.UniqueConstraint('h_specification_name')
    )
    op.create_table('l_addresses_chains',
    sa.Column('l_address_chain_id', sa.Integer(), nullable=False),
    sa.Column('h_address_id', sa.Integer(), nullable=False),
    sa.Column('h_chain_id', sa.Integer(), nullable=False),
    sa.Column('l_address_chain_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['h_address_id'], ['h_addresses.h_address_id'], ),
    sa.ForeignKeyConstraint(['h_chain_id'], ['h_chains.h_chain_id'], ),
    sa.PrimaryKeyConstraint('l_address_chain_id')
    )
    op.create_table('l_protocols_specifications',
    sa.Column('l_protocol_specification_id', sa.Integer(), nullable=False),
    sa.Column('h_protocol_id', sa.Integer(), nullable=False),
    sa.Column('h_specification_id', sa.Integer(), nullable=False),
    sa.Column('l_protocol_specification_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['h_protocol_id'], ['h_protocols.h_protocol_id'], ),
    sa.ForeignKeyConstraint(['h_specification_id'], ['h_specifications.h_specification_id'], ),
    sa.PrimaryKeyConstraint('l_protocol_specification_id')
    )
    op.create_table('l_addresses_chains_protocols_specifications',
    sa.Column('l_address_chain_protocol_specification_id', sa.Integer(), nullable=False),
    sa.Column('l_address_chain_id', sa.Integer(), nullable=False),
    sa.Column('l_protocol_specification_id', sa.Integer(), nullable=False),
    sa.Column('l_address_chain_protocol_specification_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['l_address_chain_id'], ['l_addresses_chains.l_address_chain_id'], ),
    sa.ForeignKeyConstraint(['l_protocol_specification_id'], ['l_protocols_specifications.l_protocol_specification_id'], ),
    sa.PrimaryKeyConstraint('l_address_chain_protocol_specification_id')
    )
    op.create_table('s_is_reverse',
    sa.Column('s_is_reverse_id', sa.Integer(), nullable=False),
    sa.Column('l_address_chain_protocol_specification_id', sa.Integer(), nullable=False),
    sa.Column('s_is_reverse', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['l_address_chain_protocol_specification_id'], ['l_addresses_chains_protocols_specifications.l_address_chain_protocol_specification_id'], ),
    sa.PrimaryKeyConstraint('s_is_reverse_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s_is_reverse')
    op.drop_table('l_addresses_chains_protocols_specifications')
    op.drop_table('l_protocols_specifications')
    op.drop_table('l_addresses_chains')
    op.drop_table('h_specifications')
    op.drop_table('h_protocols')
    op.drop_table('h_chains')
    op.drop_table('h_addresses')
    # ### end Alembic commands ###
